"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/*! ***************************************************************************
@license
Copyright (c) 2018 Christopher Prindle. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
******************************************************************************/
const fs = require("fs");
const Palette_1 = require("./Palette");
const buffer_1 = require("buffer");
const Helpers_1 = require("./Helpers");
const ColorConversion_1 = require("./ColorConversion");
const PaletteBuilder = Palette_1.Palette.PaletteBuilder;
/**
  * Contains file system related classes
  * @namespace
 */
var FileSystem;
(function (FileSystem) {
    /**
     * @class
     * @classdesc Provides file read and write functionality
     * @property {string} inputSource - The source file/url parsed for color values
     * @property {string} outputName  - The provided name for the generated output files
    */
    class FileAccess {
        /**
         * @constructor
         * @param {string} source - The source file/url parsed for color values
         * @param {string} name   - The provided name for the generated output files
         */
        constructor(source, name) {
            if (source) {
                this.inputSource = source;
            }
            if (name) {
                this.outputName = name;
            }
        }
        /**
         * Reads a file and sends the text to be parsed for color values
         * @public
         * @function
         * @param {Function} callback - The function to call with the input source data when complete
        */
        readFile(callback) {
            try {
                let fileData = '';
                const palette = new PaletteBuilder(this.inputSource, this.outputName);
                if (fs.existsSync(this.inputSource)) {
                    var readStream = fs.createReadStream(this.inputSource)
                        .on('data', (chunk) => {
                        fileData += buffer_1.Buffer.from(chunk);
                    })
                        .on('end', () => {
                        callback(fileData.toString());
                    });
                }
                else {
                    Helpers_1.Helpers.outputError(new Error('File does not exist'));
                }
            }
            catch (e) {
                Helpers_1.Helpers.outputError(e);
            }
        }
        /**
         * Writes color palette as a CSS file
         * @public
         * @function
         * @param {string} outputPath     - The type of stylesheet: CSS, SASS, LESS
         * @param {string} name           - The name given to the output files
         * @param {string[]} hexColors    - A string array containing the color palette as Hexadecimal values
         * @param {string} colorFormat    - CSS color format to use when writing file: Hex, HSL, or RGB
         * @param {string} styleSheetType - The type of stylesheet: CSS, SASS, LESS
         */
        writeCss(outputPath, name, hexColors, colorFormat = 'hex', styleSheetType) {
            let cssFormat = '';
            let styleSheet = '/* \n Generated by Color Seek \n https://github.com/CJPrindle/color-seek \n */\n\n';
            let count = 0;
            const colorConv = new ColorConversion_1.ColorConversion();
            let r, g, b;
            let h, s, l;
            switch (colorFormat) {
                case 'hex':
                    hexColors.forEach((hc) => {
                        cssFormat = `${hc};`;
                        styleSheet += this.formatStyleSheet(styleSheetType, cssFormat, count++);
                    });
                    break;
                case 'rgb':
                    hexColors.forEach((hc) => {
                        [r, g, b] = colorConv.HexToRgb(hc);
                        cssFormat = `rgb(${r}, ${g}, ${b});`;
                        styleSheet += this.formatStyleSheet(styleSheetType, cssFormat, count++);
                    });
                    break;
                case 'hsl':
                    hexColors.forEach((hc) => {
                        [r, g, b] = colorConv.HexToRgb(hc);
                        [h, s, l] = colorConv.RgbToHsl(r, g, b);
                        cssFormat = `hsl(${h}, ${s}%, ${l}%);`;
                        styleSheet += this.formatStyleSheet(styleSheetType, cssFormat, count++);
                    });
                    break;
            }
            const write = fs.writeFile(`${outputPath}/${name}.${styleSheetType}`, styleSheet, (err) => {
                if (err) {
                    Helpers_1.Helpers.outputError(err);
                }
            });
        }
        /**
         * Formats the color values based the file type provided
         * @private
         * @function
         * @param {string} styleSheetType - The file type to create (css, less, etc)
         * @param {string} cssFormat      - The color format to use (Hex, RGB, HSL)
         * @param {number} count          - Value used to name each color entry
         * @returns {string} A string formatted for the specified stylesheet type
         */
        formatStyleSheet(styleSheetType, cssFormat, count) {
            let output = '';
            switch (styleSheetType) {
                case 'css':
                    output += `.color-${count} { color: ${cssFormat} }\n`;
                    break;
                case 'less':
                    output += `@color-${count}: ${cssFormat}\n`;
                    break;
                case 'scss':
                    output += `$color-${count}: ${cssFormat}\n`;
                    break;
                default:
                    Helpers_1.Helpers.outputError(new Error('Invalid Stylesheet type: ' + styleSheetType));
            }
            return output;
        }
    }
    FileSystem.FileAccess = FileAccess;
})(FileSystem = exports.FileSystem || (exports.FileSystem = {}));
//# sourceMappingURL=FileSystem.js.map