/*! ***************************************************************************
@license
Copyright (c) 2018 Christopher Prindle. All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy 
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell 
copies of the Software, and to permit persons to whom the Software is 
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
IN THE SOFTWARE.
******************************************************************************/
import * as fs from 'fs';
import { Palette } from './Palette'
import { Buffer } from 'buffer';
import { Helpers } from './Helpers';
import { ColorConversion } from './ColorConversion';

const PaletteBuilder = Palette.PaletteBuilder;

/**
  * Contains file system related classes
  * @namespace
 */
export namespace FileSystem {
   /**
    * @class 
    * @classdesc Provides file read and write functionality
    * @property {string} inputSource - The source file/url parsed for color values
    * @property {string} outputName  - The provided name for the generated output files
   */
   export class FileAccess {
      public inputSource: string;
      public outputName: string;

      /**
       * @constructor
       * @param source
       * @param name
       */
      constructor(source: string, name: string) {
         if(source) {
            this.inputSource = source;
         }

         if(name) {
            this.outputName = name;
         }
      }

      /**
       * Reads a file and sends the text to be parsed for color values
       * @public
       * @function
      */
      public readFile(callback: Function): void {
         try {
            let fileData: string = '';
            let hexColors: string[] = [];

            const palette = new PaletteBuilder(this.inputSource, this.outputName);

            if(fs.existsSync(this.inputSource)) {
               var readStream = fs.createReadStream(this.inputSource)
                  .on('data', (chunk) => {
                     fileData += Buffer.from(chunk);
                  })
                  .on('end', () => {
                     callback(fileData.toString());
                  });
            } else {
               Helpers.outputError(new Error('File does not exist'));
            }
         } catch(e) {
            Helpers.outputError(e);
         }
      }

      /**
       * Writes color palette as a CSS file
       * @public
       * @function
       * @param {string} outputPath - The type of stylesheet: CSS, SASS, LESS
       * @param {string[]} hexColors    - A string array containing the color palette as Hexadecimal values
       * @param {string} colorFormat    - CSS color format to use when writing file: Hex, HSL, or RGB
       * @param {string} styleSheetType - The type of stylesheet: CSS, SASS, LESS
       */
      public writeCss(outputPath: string, name: string, hexColors: string[], colorFormat: string = 'hex',
         styleSheetType: string): void {

         let cssFormat = '';
         let styleSheet = '/* \n Generated by Color Seek \n https://github.com/CJPrindle/color-seek \n */\n\n';
         let count = 0;
         const colorConv = new ColorConversion();
         let r: number, g: number, b: number;
         let h: number, s: number, l: number;

         switch(colorFormat) {
            case 'hex':
               hexColors.forEach((hc) => {
                  cssFormat = `${hc};`;
                  styleSheet += this.formatStyleSheet(styleSheetType, cssFormat, count++);
               });
               break;
            case 'rgb':
               hexColors.forEach((hc) => {
                  [r, g, b] = colorConv.HexToRgb(hc);
                  cssFormat = `rgb(${r}, ${g}, ${b});`;
                  styleSheet += this.formatStyleSheet(styleSheetType, cssFormat, count++);
               });
               break;
            case 'hsl':
               hexColors.forEach((hc) => {
                  [r, g, b] = colorConv.HexToRgb(hc);
                  [h, s, l] = colorConv.RgbToHsl(r, g, b);
                  cssFormat = `hsl(${h}, ${s}%, ${l}%);`;
                  styleSheet += this.formatStyleSheet(styleSheetType, cssFormat, count++);
               });
               break;
         }

         const write = fs.writeFile(`${outputPath}/${name}.${styleSheetType}`, styleSheet, (err) => {
            if(err) {
               Helpers.outputError(err);
            }
         });
      }

      private formatStyleSheet(styleSheetType: string, cssFormat: string, count: number): string {
         let output = '';

         switch(styleSheetType) {
            case 'css':
               output += `.color-${count} { color: ${cssFormat} }\n`;
               break;
            case 'less':
               output += `@color-${count}: ${cssFormat}\n`;
               break;
            case 'scss':
               output += `$color-${count}: ${cssFormat}\n`;
               break;
            default:
               Helpers.outputError(new Error('Invalid Stylesheet type: ' + styleSheetType));
         }

         return output;
      }
   }
}